#!/bin/bash

# --------------------------------------------------------------
# Module Summary
#
# Prepare a list of software modules that are available on 
# Bunya. Include versions, arches, and desctiption. 
# Upload publicly to github.com.
# --------------------------------------------------------------

# Set environment source
source env/rocky8d.env

# Create log file
OUTFILE=module_summary.latest
echo "Module Summary" > $OUTFILE

# Find all modules and create a list in the working path
echo "Gather modules..." >> $OUTFILE
bash scripts/gather_modules.sh

# Process the module names
echo "Process module names..." >> $OUTFILE
python3 scripts/module_keys.py

# Create a table of modules : arches
echo "Check arches..." >> $OUTFILE
python3 scripts/module_arch_index.py

# Create a table of modules : versions
echo "Check versions..." >> $OUTFILE
python3 scripts/module_version_index.py

# Create a table of modules : whatis
echo "Check description..." >> $OUTFILE
python3 scripts/module_whatis_index.py

# Make sure output dirs exist
if [ ! -d $MODS_OUTPUT_VERSION_PATH ]
then
    mkdir -p $MODS_OUTPUT_VERSION_PATH
fi

# Create the json index of all modules with all available info
echo "Prepare json file..." >> $OUTFILE
python3 scripts/prepare_list_json.py

# Create the md list of all modules with all available info
echo "Prepare md file..." >> $OUTFILE
python3 scripts/prepare_list_md.py

# Change to output directory
cd MODS_OUTPUT_REPO_PATH
git remote set-url origin https://${GITHUB_TOKEN}@github.com/jm-rcc/module_index.git
git pull origin main
git add versions/rocky8d/*
git add versions/rocky9a/*

# Commit to github
echo "Add and commit files..." >> $OUTFILE
git commit -m "Automated commit"
git push origin main

echo "Done." >> $OUTFILE